# Generated by Django 5.0.7 on 2024-09-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brocantes_app', '0005_estado_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brocantes_app.cidade'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brocantes_app.estado'),
        ),
    ]
