# Generated by Django 5.0.7 on 2024-09-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brocantes_app', '0006_alter_instituicao_cidade_alter_instituicao_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('documento_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de Identificação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocantes_app.cidade', verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocantes_app.estado', verbose_name='Estado')),
            ],
        ),
    ]
