# Generated by Django 5.0.7 on 2024-09-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brocantes_app', '0007_doador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_controle', models.CharField(max_length=30)),
                ('link_documento_original', models.CharField(max_length=200)),
                ('link_documento_tajado', models.CharField(max_length=200)),
                ('descricao_arquivo', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('largura', models.FloatField()),
                ('comprimento', models.FloatField()),
                ('classificacao', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('digitalizado', models.BooleanField(default=False)),
                ('devolucao', models.BooleanField(default=False)),
                ('recebido', models.CharField(blank=True, max_length=20, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocantes_app.cidade')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocantes_app.doador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocantes_app.estado')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocantes_app.instituicao')),
            ],
        ),
    ]
